// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyChanges(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ApplyChanges'](arg1, arg2, arg3, arg4);
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function CreateDatabase(arg1, arg2) {
  return window['go']['app']['App']['CreateDatabase'](arg1, arg2);
}

export function DBConnect(arg1) {
  return window['go']['app']['App']['DBConnect'](arg1);
}

export function DBGetAllColumns(arg1, arg2) {
  return window['go']['app']['App']['DBGetAllColumns'](arg1, arg2);
}

export function DBGetColumns(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBGetColumns'](arg1, arg2, arg3);
}

export function DBGetDatabases(arg1) {
  return window['go']['app']['App']['DBGetDatabases'](arg1);
}

export function DBGetForeignKeys(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBGetForeignKeys'](arg1, arg2, arg3);
}

export function DBGetIndexes(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBGetIndexes'](arg1, arg2, arg3);
}

export function DBGetTables(arg1, arg2) {
  return window['go']['app']['App']['DBGetTables'](arg1, arg2);
}

export function DBGetTriggers(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBGetTriggers'](arg1, arg2, arg3);
}

export function DBQuery(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBQuery'](arg1, arg2, arg3);
}

export function DBShowCreateTable(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBShowCreateTable'](arg1, arg2, arg3);
}

export function DataSync(arg1) {
  return window['go']['app']['App']['DataSync'](arg1);
}

export function DataSyncAnalyze(arg1) {
  return window['go']['app']['App']['DataSyncAnalyze'](arg1);
}

export function DataSyncPreview(arg1, arg2, arg3) {
  return window['go']['app']['App']['DataSyncPreview'](arg1, arg2, arg3);
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function ExportData(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportData'](arg1, arg2, arg3, arg4);
}

export function ExportDatabaseSQL(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportDatabaseSQL'](arg1, arg2, arg3);
}

export function ExportQuery(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ExportQuery'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportTable(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportTable'](arg1, arg2, arg3, arg4);
}

export function ExportTablesSQL(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportTablesSQL'](arg1, arg2, arg3, arg4);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function ImportConfigFile() {
  return window['go']['app']['App']['ImportConfigFile']();
}

export function ImportData(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportData'](arg1, arg2, arg3);
}

export function InstallUpdateAndRestart() {
  return window['go']['app']['App']['InstallUpdateAndRestart']();
}

export function MySQLConnect(arg1) {
  return window['go']['app']['App']['MySQLConnect'](arg1);
}

export function MySQLGetDatabases(arg1) {
  return window['go']['app']['App']['MySQLGetDatabases'](arg1);
}

export function MySQLGetTables(arg1, arg2) {
  return window['go']['app']['App']['MySQLGetTables'](arg1, arg2);
}

export function MySQLQuery(arg1, arg2, arg3) {
  return window['go']['app']['App']['MySQLQuery'](arg1, arg2, arg3);
}

export function MySQLShowCreateTable(arg1, arg2, arg3) {
  return window['go']['app']['App']['MySQLShowCreateTable'](arg1, arg2, arg3);
}

export function OpenSQLFile() {
  return window['go']['app']['App']['OpenSQLFile']();
}

export function RedisConnect(arg1) {
  return window['go']['app']['App']['RedisConnect'](arg1);
}

export function RedisDeleteHashField(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisDeleteHashField'](arg1, arg2, arg3);
}

export function RedisDeleteKeys(arg1, arg2) {
  return window['go']['app']['App']['RedisDeleteKeys'](arg1, arg2);
}

export function RedisExecuteCommand(arg1, arg2) {
  return window['go']['app']['App']['RedisExecuteCommand'](arg1, arg2);
}

export function RedisFlushDB(arg1) {
  return window['go']['app']['App']['RedisFlushDB'](arg1);
}

export function RedisGetDatabases(arg1) {
  return window['go']['app']['App']['RedisGetDatabases'](arg1);
}

export function RedisGetServerInfo(arg1) {
  return window['go']['app']['App']['RedisGetServerInfo'](arg1);
}

export function RedisGetValue(arg1, arg2) {
  return window['go']['app']['App']['RedisGetValue'](arg1, arg2);
}

export function RedisListPush(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisListPush'](arg1, arg2, arg3);
}

export function RedisListSet(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisListSet'](arg1, arg2, arg3, arg4);
}

export function RedisRenameKey(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisRenameKey'](arg1, arg2, arg3);
}

export function RedisScanKeys(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisScanKeys'](arg1, arg2, arg3, arg4);
}

export function RedisSelectDB(arg1, arg2) {
  return window['go']['app']['App']['RedisSelectDB'](arg1, arg2);
}

export function RedisSetAdd(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisSetAdd'](arg1, arg2, arg3);
}

export function RedisSetHashField(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisSetHashField'](arg1, arg2, arg3, arg4);
}

export function RedisSetRemove(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisSetRemove'](arg1, arg2, arg3);
}

export function RedisSetString(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisSetString'](arg1, arg2, arg3, arg4);
}

export function RedisSetTTL(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisSetTTL'](arg1, arg2, arg3);
}

export function RedisTestConnection(arg1) {
  return window['go']['app']['App']['RedisTestConnection'](arg1);
}

export function RedisZSetAdd(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisZSetAdd'](arg1, arg2, arg3);
}

export function RedisZSetRemove(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisZSetRemove'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}
