// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyChanges(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ApplyChanges'](arg1, arg2, arg3, arg4);
}

export function CreateDatabase(arg1, arg2) {
  return window['go']['app']['App']['CreateDatabase'](arg1, arg2);
}

export function DBConnect(arg1) {
  return window['go']['app']['App']['DBConnect'](arg1);
}

export function DBGetAllColumns(arg1, arg2) {
  return window['go']['app']['App']['DBGetAllColumns'](arg1, arg2);
}

export function DBGetColumns(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBGetColumns'](arg1, arg2, arg3);
}

export function DBGetDatabases(arg1) {
  return window['go']['app']['App']['DBGetDatabases'](arg1);
}

export function DBGetForeignKeys(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBGetForeignKeys'](arg1, arg2, arg3);
}

export function DBGetIndexes(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBGetIndexes'](arg1, arg2, arg3);
}

export function DBGetTables(arg1, arg2) {
  return window['go']['app']['App']['DBGetTables'](arg1, arg2);
}

export function DBGetTriggers(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBGetTriggers'](arg1, arg2, arg3);
}

export function DBQuery(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBQuery'](arg1, arg2, arg3);
}

export function DBShowCreateTable(arg1, arg2, arg3) {
  return window['go']['app']['App']['DBShowCreateTable'](arg1, arg2, arg3);
}

export function DataSync(arg1) {
  return window['go']['app']['App']['DataSync'](arg1);
}

export function DataSyncAnalyze(arg1) {
  return window['go']['app']['App']['DataSyncAnalyze'](arg1);
}

export function DataSyncPreview(arg1, arg2, arg3) {
  return window['go']['app']['App']['DataSyncPreview'](arg1, arg2, arg3);
}

export function ExportData(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportData'](arg1, arg2, arg3, arg4);
}

export function ExportDatabaseSQL(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportDatabaseSQL'](arg1, arg2, arg3);
}

export function ExportQuery(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ExportQuery'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportTable(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportTable'](arg1, arg2, arg3, arg4);
}

export function ExportTablesSQL(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportTablesSQL'](arg1, arg2, arg3, arg4);
}

export function ImportConfigFile() {
  return window['go']['app']['App']['ImportConfigFile']();
}

export function ImportData(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportData'](arg1, arg2, arg3);
}

export function MySQLConnect(arg1) {
  return window['go']['app']['App']['MySQLConnect'](arg1);
}

export function MySQLGetDatabases(arg1) {
  return window['go']['app']['App']['MySQLGetDatabases'](arg1);
}

export function MySQLGetTables(arg1, arg2) {
  return window['go']['app']['App']['MySQLGetTables'](arg1, arg2);
}

export function MySQLQuery(arg1, arg2, arg3) {
  return window['go']['app']['App']['MySQLQuery'](arg1, arg2, arg3);
}

export function MySQLShowCreateTable(arg1, arg2, arg3) {
  return window['go']['app']['App']['MySQLShowCreateTable'](arg1, arg2, arg3);
}

export function OpenSQLFile() {
  return window['go']['app']['App']['OpenSQLFile']();
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}
